import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/ui/Sidebar";
import { inter, SpaceGrotesk } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr" className={`${SpaceGrotesk.variable} ${inter.variable}`}>
      <body className="font-body flex flex-row w-screen h-screen overflow-hidden">
        <Sidebar />

        <main id="main-content" className="relative flex-1 h-screen overflow-y-auto">
          <div className="relative min-h-full">
            <div className="absolute inset-0 flex justify-evenly pointer-events-none z-[-1]">
              {[...Array(4)].map((_, i) => (
                <div 
                  key={i}
                  className="w-px h-full bg-border_color"
                />
              ))}
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}

