import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/ui/Sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-row w-screen overflow-x-hidden">
        <Sidebar />
        <main className="relative flex-1 min-h-screen">
          {/* Grille de lignes en arrière-plan */}
          <div className="absolute inset-0 flex justify-evenly pointer-events-none z-[-1]">
            <div className="w-px h-full bg-border_color"></div>
            <div className="w-px h-full bg-border_color"></div>
            <div className="w-px h-full bg-border_color"></div>
            <div className="w-px h-full bg-border_color"></div>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
